spring.application.name=registrasi


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Database Credentials and URL (default values provided)
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/api_registrasi}


# Connection Pool (HikariCP)
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# Disable Hibernate usage of JDBC metadata
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.format_sql=true

# Health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Role User
app.security.user-role=USER
app.security.admin-role=ADMIN
app.security.public-urls=/login,/request/user
app.security.admin-urls=/tokyodev/api/create,/laporan/**,/create/roll
app.security.user-urls=/tokyodev/api/search

jwt.secret.key=my-very-strong-and-long-secret-key-for-jwt

spring.main.allow-circular-references=true

logging.level.org.apache.catalina.session=DEBUG
logging.level.org.apache.catalina.authenticator=DEBUG


